# ============================
# Base Image
# ============================
FROM node:18-slim AS base
ENV CI=true

# ============================
# Dependency Installation
# ============================
FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

# ============================
# Build Stage
# ============================
FROM base AS builder
WORKDIR /app

# ---- Public (Frontend) ENV ----
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_DOMAIN_URL
ARG NEXT_PUBLIC_DASHBOARD_URL

ARG NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
ARG NEXT_PUBLIC_EMAILJS_PUBLIC_KEY
ARG NEXT_PUBLIC_EMAILJS_SERVICE_ID

ARG NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ARG NEXT_PUBLIC_HUBSPOT_FORM_GUID

# ---- Server-side (Backend) ENV ----
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG STRIPE_PUBLISHABLE_KEY

ARG STRIPE_PRICE_ID_STUDENT_TRIAL_WEEKLY
ARG STRIPE_PRICE_ID_STUDENT_BASIC_MONTHLY
ARG STRIPE_PRICE_ID_STUDENT_BASIC_YEARLY
ARG STRIPE_PRICE_ID_STUDENT_PLUS_MONTHLY
ARG STRIPE_PRICE_ID_STUDENT_PLUS_YEARLY
ARG STRIPE_PRICE_ID_TEACHER_PLUS_MONTHLY
ARG STRIPE_PRICE_ID_TEACHER_PLUS_YEARLY

ARG MONGO_URI
ARG DOMAIN_URL
ARG JWT_SECRET

# ---- Export env for build ----
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_DOMAIN_URL=$NEXT_PUBLIC_DOMAIN_URL
ENV NEXT_PUBLIC_DASHBOARD_URL=$NEXT_PUBLIC_DASHBOARD_URL

ENV NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=$NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
ENV NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=$NEXT_PUBLIC_EMAILJS_PUBLIC_KEY
ENV NEXT_PUBLIC_EMAILJS_SERVICE_ID=$NEXT_PUBLIC_EMAILJS_SERVICE_ID

ENV NEXT_PUBLIC_HUBSPOT_PORTAL_ID=$NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ENV NEXT_PUBLIC_HUBSPOT_FORM_GUID=$NEXT_PUBLIC_HUBSPOT_FORM_GUID

ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
ENV STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY

ENV STRIPE_PRICE_ID_STUDENT_TRIAL_WEEKLY=$STRIPE_PRICE_ID_STUDENT_TRIAL_WEEKLY
ENV STRIPE_PRICE_ID_STUDENT_BASIC_MONTHLY=$STRIPE_PRICE_ID_STUDENT_BASIC_MONTHLY
ENV STRIPE_PRICE_ID_STUDENT_BASIC_YEARLY=$STRIPE_PRICE_ID_STUDENT_BASIC_YEARLY
ENV STRIPE_PRICE_ID_STUDENT_PLUS_MONTHLY=$STRIPE_PRICE_ID_STUDENT_PLUS_MONTHLY
ENV STRIPE_PRICE_ID_STUDENT_PLUS_YEARLY=$STRIPE_PRICE_ID_STUDENT_PLUS_YEARLY
ENV STRIPE_PRICE_ID_TEACHER_PLUS_MONTHLY=$STRIPE_PRICE_ID_TEACHER_PLUS_MONTHLY
ENV STRIPE_PRICE_ID_TEACHER_PLUS_YEARLY=$STRIPE_PRICE_ID_TEACHER_PLUS_YEARLY

ENV MONGO_URI=$MONGO_URI
ENV DOMAIN_URL=$DOMAIN_URL
ENV JWT_SECRET=$JWT_SECRET

# ---- Build ----
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# ============================
# Production Runtime Stage
# ============================
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy assets
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Runtime user
USER nextjs
EXPOSE 3000

CMD ["npm", "start"]
